<?php $render('partial/header', $data); ?>

<h1>Create Product</h1>

<!--TODO: Implement like login-->

<?php //$beginForm('Product', 'CreateProduct', method: 'post'); ?>
<!--<div class="mb-3">-->
<!--    <label for="userName" class="form-label">User name</label>-->
<!--    <input class="form-control" id="username" name="un" value="--><?php //$htmlOut($data['userName']); ?><!--"/>-->
<!--</div>-->
<!--<div class="mb-3">-->
<!--    <label for="password" class="form-label">Password</label>-->
<!--    <input class="form-control" type="password" id="password" name="password" />-->
<!--</div>-->
<!--<div class="mb-3">-->
<!--    <label for=""></label>-->
<!--</div>-->
<!--<button class="btn btn-primary">Create</button>-->
<?php //$endForm(); ?>

<?php $render('partial/footer', $data); ?>
